version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: unless-stopped
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/dojo-outubro/src
    restart: unless-stopped
    command: bash -c "npm install && npm install -g nodemon && nodemon src/server.js"
    environment:
      - MONGO_URL=mongodb://mongo:27017/ecommerce
    volumes:
      - .:/usr/dojo-outubro/src/
      - ./package.json:/usr/src/dojo-outubro/package.json
    ports:
      - "3000:3000"
    links:
      - mongo
