version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: unless-stopped
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:12
    working_dir: /usr/dojo/src
    restart: unless-stopped
    command: bash -c "npm install && npm run dev"
    environment:
      - MONGO_URL=mongodb://mongo:27017/artemis
    volumes:
      - .:/usr/artemis/src/
      - ./package.json:/usr/src/artemis/package.json
    ports:
      - "5000:5000"
    links:
      - mongo
